### PR TITLE
Make it clear wayland is required

### PR DESCRIPTION
**Pull request by Quackdoc**
solves https://github.com/waydroid/waydroid/issues/1359  and many others

### CODE REVIEW

**Comment by aleasto** [comment]
Can we also remove "like Ubuntu"? I don't feel like it belongs, especially now with the added "running Wayland"

**Comment by Quackdoc** [comment]
Agreed all three sound good in my book, any preference?

A) "A container-based approach to boot a full Android system on a regular GNU/Linux systems running Wayland"
B) "A container-based approach to boot a full Android system on a regular GNU/Linux systems running Wayland based desktop environments"
C) "A container-based approach to boot a full Android system on a regular GNU/Linux systems running Wayland compositors"

**Comment by aleasto** [comment]
Maybe B.
Also you made _systems_ plural so remove the _a_ article

**Comment by aleasto** [comment]
Thanks

**Pull request merged**
